package redhat.poc.testdoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimDoc implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ClaimDoc() {
    }

}