package redhat.poc.testdoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class ClaimsDoc implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String docid;

   public ClaimsDoc()
   {
   }

   public java.lang.String getDocid()
   {
      return this.docid;
   }

   public void setDocid(java.lang.String docid)
   {
      this.docid = docid;
   }

   public ClaimsDoc(java.lang.String docid)
   {
      this.docid = docid;
   }

}