package redhat.poc.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Claim Id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Claim Type")
   private java.lang.String type;
   private double amount;
   private java.util.Date claimdate;

   public Claim()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public double getAmount()
   {
      return this.amount;
   }

   public void setAmount(double amount)
   {
      this.amount = amount;
   }

   public java.util.Date getClaimdate()
   {
      return this.claimdate;
   }

   public void setClaimdate(java.util.Date claimdate)
   {
      this.claimdate = claimdate;
   }

   public Claim(java.lang.String id, java.lang.String type, double amount,
         java.util.Date claimdate)
   {
      this.id = id;
      this.type = type;
      this.amount = amount;
      this.claimdate = claimdate;
   }

}