package redhat.poc.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ErrorContext implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ErrorContext() {
    }

}