package redhat.poc.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
@org.kie.api.remote.Remotable
@XmlRootElement
public class ProviderInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String address;
   private java.lang.String city;
   private java.lang.String state;
   private java.lang.String zip;

   public ProviderInfo()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }
   @XmlElement
   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }
   @XmlElement
   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }
   @XmlElement
   public void setCity(java.lang.String city)
   {
      this.city = city;
   }
   @XmlElement
   public java.lang.String getState()
   {
      return this.state;
   }
   @XmlElement
   public void setState(java.lang.String state)
   {
      this.state = state;
   }
   @XmlElement
   public java.lang.String getZip()
   {
      return this.zip;
   }
   @XmlElement
   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public ProviderInfo(java.lang.String name, java.lang.String address,
         java.lang.String city, java.lang.String state, java.lang.String zip)
   {
      this.name = name;
      this.address = address;
      this.city = city;
      this.state = state;
      this.zip = zip;
   }

@Override
public String toString() {
	return "ProviderInfo [name=" + name + ", address=" + address + ", city="
			+ city + ", state=" + state + ", zip=" + zip + "]";
}

}