package redhat.poc.claim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("claim Id")
   private java.lang.String id;

   private java.lang.String documentId;

   @org.kie.api.definition.type.Label("claim date")
   private java.util.Date date;

   private double claimAmount;

   private redhat.poc.claim.ProviderInfo providerInfo;

   private redhat.poc.claim.Address address;

   private redhat.poc.claim.Member member;

   private java.lang.String claimworker;

   private java.lang.String claimsupervisor;

   private java.lang.String status;

   private java.lang.String errorType;

   private java.lang.String errorCode;

   public Claim()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getDocumentId()
   {
      return this.documentId;
   }

   public void setDocumentId(java.lang.String documentId)
   {
      this.documentId = documentId;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public double getClaimAmount()
   {
      return this.claimAmount;
   }

   public void setClaimAmount(double claimAmount)
   {
      this.claimAmount = claimAmount;
   }

   public redhat.poc.claim.ProviderInfo getProviderInfo()
   {
      return this.providerInfo;
   }

   public void setProviderInfo(redhat.poc.claim.ProviderInfo providerInfo)
   {
      this.providerInfo = providerInfo;
   }

   public redhat.poc.claim.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(redhat.poc.claim.Address address)
   {
      this.address = address;
   }

   public redhat.poc.claim.Member getMember()
   {
      return this.member;
   }

   public void setMember(redhat.poc.claim.Member member)
   {
      this.member = member;
   }

   public java.lang.String getClaimworker()
   {
      return this.claimworker;
   }

   public void setClaimworker(java.lang.String claimworker)
   {
      this.claimworker = claimworker;
   }

   public java.lang.String getClaimsupervisor()
   {
      return this.claimsupervisor;
   }

   public void setClaimsupervisor(java.lang.String claimsupervisor)
   {
      this.claimsupervisor = claimsupervisor;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String getErrorType()
   {
      return this.errorType;
   }

   public void setErrorType(java.lang.String errorType)
   {
      this.errorType = errorType;
   }

   public java.lang.String getErrorCode()
   {
      return this.errorCode;
   }

   public void setErrorCode(java.lang.String errorCode)
   {
      this.errorCode = errorCode;
   }

   public Claim(java.lang.String id, java.lang.String documentId,
         java.util.Date date, double claimAmount,
         redhat.poc.claim.ProviderInfo providerInfo,
         redhat.poc.claim.Address address, redhat.poc.claim.Member member,
         java.lang.String claimworker, java.lang.String claimsupervisor,
         java.lang.String status, java.lang.String errorType,
         java.lang.String errorCode)
   {
      this.id = id;
      this.documentId = documentId;
      this.date = date;
      this.claimAmount = claimAmount;
      this.providerInfo = providerInfo;
      this.address = address;
      this.member = member;
      this.claimworker = claimworker;
      this.claimsupervisor = claimsupervisor;
      this.status = status;
      this.errorType = errorType;
      this.errorCode = errorCode;
   }

}