package redhat.poc.claim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "claim Id")
   private java.lang.String id;
   private java.lang.String documentId;
   @org.kie.api.definition.type.Label(value = "claim date")
   private java.util.Date date;
   private double claimAmount;

   public Claim()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getDocumentId()
   {
      return this.documentId;
   }

   public void setDocumentId(java.lang.String documentId)
   {
      this.documentId = documentId;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public double getClaimAmount()
   {
      return this.claimAmount;
   }

   public void setClaimAmount(double claimAmount)
   {
      this.claimAmount = claimAmount;
   }

   public Claim(java.lang.String id, java.lang.String documentId,
         java.util.Date date, double claimAmount)
   {
      this.id = id;
      this.documentId = documentId;
      this.date = date;
      this.claimAmount = claimAmount;
   }

}