package redhat.poc.claim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Service implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Service() {
    }

}