package redhat.poc.claim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Service implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int id;
   private java.lang.String code;
   private java.util.Date serviceDate;
   private double serviceAmount;
   private double allowableAmount;

   public Service()
   {
   }

   public int getId()
   {
      return this.id;
   }

   public void setId(int id)
   {
      this.id = id;
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.util.Date getServiceDate()
   {
      return this.serviceDate;
   }

   public void setServiceDate(java.util.Date serviceDate)
   {
      this.serviceDate = serviceDate;
   }

   public double getServiceAmount()
   {
      return this.serviceAmount;
   }

   public void setServiceAmount(double serviceAmount)
   {
      this.serviceAmount = serviceAmount;
   }

   public double getAllowableAmount()
   {
      return this.allowableAmount;
   }

   public void setAllowableAmount(double allowableAmount)
   {
      this.allowableAmount = allowableAmount;
   }

   public Service(int id, java.lang.String code, java.util.Date serviceDate,
         double serviceAmount, double allowableAmount)
   {
      this.id = id;
      this.code = code;
      this.serviceDate = serviceDate;
      this.serviceAmount = serviceAmount;
      this.allowableAmount = allowableAmount;
   }

}